/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1.Programs;

import com.mycompany.mavenproject1.Models.Ganso;
import com.mycompany.mavenproject1.Models.Guerreiro;
import com.mycompany.mavenproject1.Models.Heroi;
import com.mycompany.mavenproject1.Models.Inimigo;
import com.mycompany.mavenproject1.Models.Mago;
import javax.swing.ImageIcon;

/**
 *
 * @author CLIENTE
 */
public class TelaBatalha extends javax.swing.JFrame {

    /**
     * Creates new form TelaBatalha
     */
   
    
    protected Guerreiro guerr;
    protected Ganso gans;
    protected Mago mag;
    protected Inimigo inimg;
    
    public TelaBatalha(Heroi personagem , Integer designador, Heroi inimigo) {
        initComponents();
        
        if(designador == 1){
            System.out.println("Guerreiro");
        }
        else if(designador == 2){
            System.out.println("GANSO");
        }
        else if(designador == 3){
            System.out.println("Mago");
        }
        
        ImageIcon heroImage = new ImageIcon(personagem.getNomeImg());
        ImageIcon gitImage =  new ImageIcon(inimigo.getNomeImg());
        
        lbHeroi.setText("");
        lbHeroi.setIcon(heroImage);
        
        lbNome.setText(personagem.getNome());
        lbVilaoNome.setText(inimigo.getNome());
        
        lbVilao.setText("");
        lbVilao.setIcon(gitImage);
        
        pbGitVida.setMaximum(inimigo.getVida());
        pbGitStamina.setMaximum(inimigo.getStamina());
        
        pbHeroiVida.setMaximum(personagem.getVida());
        pbHeroiStamina.setMaximum(personagem.getStamina());
        
        pbGitStamina.setValue(inimigo.getStamina());
        pbGitVida.setValue(inimigo.getVida());
        
        pbHeroiVida.setValue(personagem.getVida());
        pbHeroiStamina.setValue(personagem.getStamina());
        
        
        Guerreiro guerr = new Guerreiro(personagem.getNome(), personagem.getVida(), personagem.getStamina(), personagem.getEspecial(), personagem.getNomeImg());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        lbHeroi = new javax.swing.JLabel();
        lbVilao = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pbHeroiVida = new javax.swing.JProgressBar();
        pbHeroiStamina = new javax.swing.JProgressBar();
        pbGitVida = new javax.swing.JProgressBar();
        lbNome = new javax.swing.JLabel();
        lbVilaoNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbEspecial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pbGitStamina = new javax.swing.JProgressBar();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbHeroi.setText("placeholder");

        lbVilao.setText("placeholder");

        jButton2.setText("Atacar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Descansar");

        jButton4.setText("Magia");

        jButton5.setText("Especial");

        pbHeroiVida.setBackground(new java.awt.Color(255, 102, 102));

        lbNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbNome.setText("jLabel1");

        lbVilaoNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbVilaoNome.setText("THE FORBBIDEN ONE");

        jLabel1.setText("Especial: ");

        lbEspecial.setText("0");

        jLabel3.setText("/5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addComponent(pbHeroiVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbHeroiStamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHeroi)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVilaoNome)
                    .addComponent(lbVilao)
                    .addComponent(pbGitVida, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbGitStamina, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jLabel1)
                    .addComponent(lbEspecial)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbHeroiVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbGitVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pbHeroiStamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pbGitStamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbVilao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbHeroi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbVilaoNome))
                .addGap(155, 155, 155))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //guerr.atacarFisico(persona, ICONIFIED, guerr, SOMEBITS, SOMEBITS);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbEspecial;
    private javax.swing.JLabel lbHeroi;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbVilao;
    private javax.swing.JLabel lbVilaoNome;
    private javax.swing.JProgressBar pbGitStamina;
    private javax.swing.JProgressBar pbGitVida;
    private javax.swing.JProgressBar pbHeroiStamina;
    private javax.swing.JProgressBar pbHeroiVida;
    // End of variables declaration//GEN-END:variables
}
